version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: minitwitter-postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minitwitter
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
